services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://username:password@db:5432/postgresdb
      - SYNC_DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - SECRET_KEY=your_super_secret_key_here_change_me
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    working_dir: /app/src

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  celery:
    build: .
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - db
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://username:password@db:5432/postgresdb
      - SYNC_DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - SECRET_KEY=your_super_secret_key_here_change_me
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    working_dir: /app/src

  celery-beat:
    build: .
    command: celery -A celery_app.celery_app beat --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - db
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://username:password@db:5432/postgresdb
      - SYNC_DATABASE_URL=postgresql://username:password@db:5432/postgresdb
      - SECRET_KEY=your_super_secret_key_here_change_me
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    working_dir: /app/src

volumes:
  postgres_data:
